# Generated by Django 4.2.5 on 2023-10-08 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("exames", "0002_auto_20231008_1318"),
    ]

    operations = [
        migrations.AlterField(
            model_name="acessomedico",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="pedidosexames",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="solicitacaoexame",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="tiposexames",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
